version: '3.8'

services:
  proxybot:
    build: .
    image: mybot:latest
    container_name: telegram-proxy-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      # Если нужен прокси для доступа к API Telegram, раскомментируйте:
      # - PROXY_URL=socks5://172.17.0.1:1080
